/**
 * Clase que gestiona la ventana principal de la aplicación, con la rejilla principal
 * de datos. Incluye un botón para la inclusión de nuevos registros.
 */
package ConexionFirebird2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * @author Carlos León Remedios
 * 2º DAM - Acceso a Datos
 * Ejercicio 12/03/2018
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Datos conexion = new Datos();
    private ResultSet rs;
    private DefaultTableModel dtm;
    
    public VentanaPrincipal() throws SQLException {
        initComponents();
        conexion.conectar();
        mostrarTabla();
        this.setTitle("Clientes:");
    }
    
    public void mostrarTabla() throws SQLException{
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[] {"NIF", "Nombre"});
        rs = conexion.consultarClientes();
        try {
            while (rs.next()){
                dtm.addRow(new String[] {rs.getString("NIF"), rs.getString("NOMBRE")});
            }
        } catch (SQLException sqle){
            System.out.println("Error consulta creación de tabla:\n"+sqle.getMessage());
        }
        tablaClientes.setModel(dtm);
        rs.close();
        dtm.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaClientes.setToolTipText("");
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaClientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNuevo)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        VentanaCliente vc = new VentanaCliente(this, true);
        vc.nuevoCliente();
        vc.setVisible(true);
        try {
            mostrarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btNuevoActionPerformed

    private void tablaClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMousePressed
        if(evt.getClickCount()==2){
            VentanaCliente vc = new VentanaCliente(this, true);
            String nif = (String)tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0);
            rs = conexion.consultarCliente(nif);
            try {
                while (rs.next()){
                    vc.recibeCliente(rs.getString("nif"), rs.getString("Nombre"), 
                            rs.getString("Direccion"), rs.getString("Telefono"));
                }
            } catch (SQLException sqlex){
                System.out.println("Error consulta de cliente:\n"+sqlex.getMessage());
            }
            vc.setVisible(true);
            try {
                mostrarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_tablaClientesMousePressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
